/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require("google-protobuf");
var goog = jspb;
var global = Function("return this")();
var proto = { storepb: require("./storeapi_pb") };
const COMPILED = true;

goog.exportSymbol("proto.storepb.GetBrowseManifestInbound", null, global);
goog.exportSymbol("proto.storepb.GetBrowseManifestOutbound", null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.storepb.GetBrowseManifestInbound = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.storepb.GetBrowseManifestInbound.repeatedFields_,
    null
  );
};
goog.inherits(proto.storepb.GetBrowseManifestInbound, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.storepb.GetBrowseManifestInbound.displayName =
    "proto.storepb.GetBrowseManifestInbound";
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.storepb.GetBrowseManifestInbound.repeatedFields_ = [1];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.storepb.GetBrowseManifestInbound.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.storepb.GetBrowseManifestInbound.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.storepb.GetBrowseManifestInbound} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.storepb.GetBrowseManifestInbound.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        flagsList: jspb.Message.getRepeatedField(msg, 1),
        userid: jspb.Message.getFieldWithDefault(msg, 2, ""),
        originid: jspb.Message.getFieldWithDefault(msg, 3, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.storepb.GetBrowseManifestInbound}
 */
proto.storepb.GetBrowseManifestInbound.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.storepb.GetBrowseManifestInbound();
  return proto.storepb.GetBrowseManifestInbound.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.storepb.GetBrowseManifestInbound} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.storepb.GetBrowseManifestInbound}
 */
proto.storepb.GetBrowseManifestInbound.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.addFlags(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setUserid(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setOriginid(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.storepb.GetBrowseManifestInbound.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.storepb.GetBrowseManifestInbound.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.storepb.GetBrowseManifestInbound} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.storepb.GetBrowseManifestInbound.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getFlagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(1, f);
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getOriginid();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
};

/**
 * repeated string flags = 1;
 * @return {!Array<string>}
 */
proto.storepb.GetBrowseManifestInbound.prototype.getFlagsList = function () {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};

/** @param {!Array<string>} value */
proto.storepb.GetBrowseManifestInbound.prototype.setFlagsList = function (
  value
) {
  jspb.Message.setField(this, 1, value || []);
};

/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.storepb.GetBrowseManifestInbound.prototype.addFlags = function (
  value,
  opt_index
) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};

proto.storepb.GetBrowseManifestInbound.prototype.clearFlagsList = function () {
  this.setFlagsList([]);
};

/**
 * optional string userID = 2;
 * @return {string}
 */
proto.storepb.GetBrowseManifestInbound.prototype.getUserid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/** @param {string} value */
proto.storepb.GetBrowseManifestInbound.prototype.setUserid = function (value) {
  jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string originID = 3;
 * @return {string}
 */
proto.storepb.GetBrowseManifestInbound.prototype.getOriginid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/** @param {string} value */
proto.storepb.GetBrowseManifestInbound.prototype.setOriginid = function (
  value
) {
  jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.storepb.GetBrowseManifestOutbound = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.storepb.GetBrowseManifestOutbound, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.storepb.GetBrowseManifestOutbound.displayName =
    "proto.storepb.GetBrowseManifestOutbound";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.storepb.GetBrowseManifestOutbound.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.storepb.GetBrowseManifestOutbound.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.storepb.GetBrowseManifestOutbound} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.storepb.GetBrowseManifestOutbound.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        manifest: jspb.Message.getFieldWithDefault(msg, 1, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.storepb.GetBrowseManifestOutbound}
 */
proto.storepb.GetBrowseManifestOutbound.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.storepb.GetBrowseManifestOutbound();
  return proto.storepb.GetBrowseManifestOutbound.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.storepb.GetBrowseManifestOutbound} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.storepb.GetBrowseManifestOutbound}
 */
proto.storepb.GetBrowseManifestOutbound.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setManifest(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.storepb.GetBrowseManifestOutbound.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.storepb.GetBrowseManifestOutbound.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.storepb.GetBrowseManifestOutbound} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.storepb.GetBrowseManifestOutbound.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getManifest();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
};

/**
 * optional string manifest = 1;
 * @return {string}
 */
proto.storepb.GetBrowseManifestOutbound.prototype.getManifest = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/** @param {string} value */
proto.storepb.GetBrowseManifestOutbound.prototype.setManifest = function (
  value
) {
  jspb.Message.setProto3StringField(this, 1, value);
};

goog.object.extend(exports, proto.storepb);
