apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: thundrcld.com/account:latest
          command: ["./main"]
          ports:
            - containerPort: 42069
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  ports:
  - name: grpc-web
    port: 42069
  selector:
    app: account


  